In [1]:
import numpy as np

In [5]:
a=np.random.randint(30,99,(7,8))
a

array([[91, 82, 54, 36, 62, 68, 37, 58],
       [40, 35, 70, 59, 73, 81, 45, 54],
       [67, 52, 71, 34, 42, 58, 97, 59],
       [83, 45, 31, 55, 76, 76, 84, 85],
       [38, 86, 48, 90, 74, 74, 33, 44],
       [32, 61, 31, 96, 96, 96, 46, 57],
       [84, 88, 40, 30, 76, 74, 31, 52]])

In [9]:
np.random.seed(55)
a=np.random.randint(30,90,20)

In [14]:
a.shape

(20,)

In [44]:
b=np.random.randint(20,80,(8,9))
b

array([[49, 52, 79, 76, 62, 54, 76, 48, 21],
       [32, 43, 38, 47, 50, 45, 22, 76, 40],
       [73, 62, 69, 49, 30, 65, 21, 51, 70],
       [78, 64, 66, 23, 36, 54, 25, 48, 32],
       [74, 59, 33, 48, 41, 59, 72, 67, 26],
       [32, 68, 63, 72, 61, 36, 68, 41, 72],
       [61, 20, 71, 75, 76, 38, 55, 76, 25],
       [46, 73, 56, 31, 35, 33, 58, 46, 36]])

In [47]:
b.shape

(8, 9)

In [49]:
b.ndim

2

### array[row_start: row_end : row_step , col_start: col end:col_step]

In [52]:
b[2:6]

array([[73, 62, 69, 49, 30, 65, 21, 51, 70],
       [78, 64, 66, 23, 36, 54, 25, 48, 32],
       [74, 59, 33, 48, 41, 59, 72, 67, 26],
       [32, 68, 63, 72, 61, 36, 68, 41, 72]])

In [54]:
b[2:6:2,1:7:2]

array([[62, 49, 65],
       [59, 48, 59]])

In [56]:
b[1:5,1:6]

array([[43, 38, 47, 50, 45],
       [62, 69, 49, 30, 65],
       [64, 66, 23, 36, 54],
       [59, 33, 48, 41, 59]])

In [ ]:
the pandas

In [60]:
import pandas as pd

In [109]:
k=[[4,7],[2,19],[50,60]]
k

[[4, 7], [2, 19], [50, 60]]

In [111]:
np.array(k)

array([[ 4,  7],
       [ 2, 19],
       [50, 60]])

In [113]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2, 19],
       [50, 60]])

In [115]:
t.ndim

2

In [117]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (3, 2) instead

In [ ]:
pd.DataFrame(t)

In [120]:
pd.DataFrame(k,columns=['name','sub'],index=[289,300,389])

name  sub
289     4    7
300     2   19
389    50   60

NameError: name 'df' is not defined